[package]
name = "qdrant"
version = "0.11.5"
authors = ["Andrey Vasnetsov <andrey@vasnetsov.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["web", "parking_lot"]
web = ["actix-web"]
service_debug = ["parking_lot", "parking_lot/deadlock_detection"]

[dev-dependencies]
rusty-hook = "^0.11.2"
tempfile = "3.3.0"

[dependencies]

parking_lot = { version = "0.12.1", features = ["deadlock_detection"], optional = true }

anyhow = "1.0.66"
atty = "0.2"
chrono = { version = "~0.4", features = ["serde"] }
clap = { version = "4.0.27", features = ["derive"] }
colored = "2"
env_logger = "0.10.0"
futures = "0.3.25"
futures-util = "0.3.24"
itertools = "0.10"
log = "0.4"
num_cpus = "1.14"
schemars = { version = "0.8.11", features = ["uuid1", "preserve_order", "chrono"] }
serde = { version = "~1.0", features = ["derive"] }
serde_cbor = { version = "0.11.2" }
serde_json = "~1.0"
sys-info = "0.9.1"
thiserror = "1.0"
uuid = { version = "1.2", features = ["v4", "serde"] }

config = "~0.13.3"

tokio = { version = "~1.23", features = ["full"] }

actix-cors = "0.6.4"
actix-files = "0.6.2"
actix-web = { version = "4.2.1", optional = true }
num-traits = "0.2.15"
tar = "0.4.38"
tonic = { version = "0.7.2", features = ["compression"] }
tower = "0.4.13"
tower-layer = "0.3.2"

# Consensus related crates
prost = "=0.9.0"
raft = { git = "https://github.com/tikv/raft-rs", rev = "52d84aac8734369d81c2d77413ea3ab8e58e0af9", features = [
    "prost-codec",
], default-features = false }
raft-proto = { git = "https://github.com/tikv/raft-rs", rev = "52d84aac8734369d81c2d77413ea3ab8e58e0af9", features = [
    "prost-codec",
], default-features = false }
slog = "2.7.0"
slog-stdlog = "4.1.1"

api = { path = "lib/api" }
collection = { path = "lib/collection" }
segment = { path = "lib/segment" }
storage = { path = "lib/storage" }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"

[[bin]]
name = "schema_generator"
path = "src/schema_generator.rs"
test = false
bench = false

[workspace]
members = ["lib/*"]
