version: "3.7"

services:
  qdrant_1:
    image: qdrant-dev:latest
    command: ./qdrant --uri 'http://qdrant_1:6335'
    restart: always
    environment:
      - QDRANT__LOG_LEVEL=debug,raft=info
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__CLUSTER__P2P__PORT=6335
      - QDRANT__CLUSTER__ENABLED=true
      - QDRANT__CLUSTER__CONSENSUS__TICK_PERIOD_MS=100
      - QDRANT__CLUSTER__CONSENSUS__BOOTSTRAP_TIMEOUT_SEC=15
      - QDRANT__CLUSTER__CONSENSUS__MESSAGE_TIMEOUT_TICKS=2
      - TOKIO_CONSOLE_BIND=0.0.0.0:6669
    ports:
      - "127.0.0.1:6333:6333"
      - "127.0.0.1:6334:6334"
      - "127.0.0.1:6669:6669" # Tokio Console
      - "127.0.0.1:8086:8086" # Tracy
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.2"

  qdrant_2:
    image: qdrant-dev:latest
    command: bash -c "sleep 5 && ./qdrant --bootstrap 'http://qdrant_1:6335' --uri 'http://qdrant_2:6335'"
    restart: always
    environment:
      - QDRANT__LOG_LEVEL=debug,raft=info
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__CLUSTER__P2P__PORT=6335
      - QDRANT__CLUSTER__ENABLED=true
      - QDRANT__CLUSTER__CONSENSUS__TICK_PERIOD_MS=100
      - QDRANT__CLUSTER__CONSENSUS__BOOTSTRAP_TIMEOUT_SEC=15
      - QDRANT__CLUSTER__CONSENSUS__MESSAGE_TIMEOUT_TICKS=2
    ports:
      - "127.0.0.1:6343:6333"
      - "127.0.0.1:6344:6334"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.2"

  qdrant_3:
    image: qdrant-dev:latest
    command: bash -c "sleep 10 && ./qdrant --bootstrap 'http://qdrant_1:6335' --uri 'http://qdrant_3:6335'"
    restart: always
    environment:
      - QDRANT__LOG_LEVEL=debug,raft=info
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__CLUSTER__P2P__PORT=6335
      - QDRANT__CLUSTER__ENABLED=true
      - QDRANT__CLUSTER__CONSENSUS__TICK_PERIOD_MS=100
      - QDRANT__CLUSTER__CONSENSUS__BOOTSTRAP_TIMEOUT_SEC=15
      - QDRANT__CLUSTER__CONSENSUS__MESSAGE_TIMEOUT_TICKS=2
    ports:
      - "127.0.0.1:6353:6333"
      - "127.0.0.1:6354:6334"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.2"
