#@ load("openapi.lib.yml", "response", "reference", "type", "array")

paths:
  /telemetry:
    get:
      summary: Collect telemetry data
      description: Collect telemetry data including app info, system info, collections info, cluster info, configs and statistics
      operationId: telemetry
      tags:
        - service
      parameters:
        - name: anonymize
          in: query
          description: "If true, anonymize result"
          required: false
          schema:
            type: boolean
      responses: #@ response(array(reference("TelemetryData")))

  /write_lock:
    put:
      summary: Set write lock
      description: Set write lock. If disabled, all write operations and collections creation are forbidden. Returns previous lock value
      operationId: put_write_lock
      tags:
        - service
      requestBody:
        description: Lock status and optional error message
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WriteLockStatus"
      responses: #@ response(type("boolean"))

    get:
      summary: Get write lock enable
      description:  If false, all write operations and collections creation are forbidden
      operationId: get_write_lock
      tags:
        - service
      responses: #@ response(type("boolean"))
