name: Docker Build and Push dev branch images

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: Swatinem/rust-cache@v2
        - name: Get current tag
          id: vars
          run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        - name: Build the Docker image
          env:
            RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
          run: |
            # Create build container
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker buildx create --use

            # Authenticate on registries
            docker login --username generall --password ${{ secrets.DOCKERHUB_TOKEN }}
            docker login https://docker.pkg.github.com -u qdrant --password ${{ secrets.GITHUB_TOKEN }}

            # Build regular image for Docker Hub
            DOCKERHUB_TAG="qdrant/qdrant:dev-${{ github.sha }}"
            DOCKERHUB_TAG_LATEST="qdrant/qdrant:dev"
            TAGS="-t ${DOCKERHUB_TAG} -t ${DOCKERHUB_TAG_LATEST}"
            GITHUB_TAG="docker.pkg.github.com/qdrant/qdrant/qdrant:dev-${{ github.sha }}"

            # Pull, retag and push to GitHub packages
            docker buildx build --platform='linux/amd64,linux/arm64' $TAGS --push --label "org.opencontainers.image.revision"=${{ github.sha }} .
            docker pull $DOCKERHUB_TAG
            docker tag $DOCKERHUB_TAG $GITHUB_TAG
            docker push $GITHUB_TAG
