name: Build and deploy docker image

on:
  workflow_dispatch:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'           # Push events to every tag not containing /
    branches: [ multiplatform-build-fix ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v1
    - name: Get current tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: generall
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to Github
      uses: docker/login-action@v2
      with:
        registry: https://docker.pkg.github.com
        username: qdrant
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: |
          generall/qdrant:${{ github.ref_name }}
          docker.pkg.github.com/qdrant/qdrant/qdrant:${{ github.ref_name }}
        platforms: linux/amd64,linux/arm64
        push: true
