name: Build and deploy docker image

on:
  workflow_dispatch:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'           # Push events to every tag not containing /
    branches: [ multiplatform-build-fix ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v1
    - name: Get current tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Create docker buildx and qemu
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx create --use

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: generall
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to Github
      uses: docker/login-action@v2
      with:
        registry: https://docker.pkg.github.com
        username: qdrant
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: |
          generall/qdrant:${{ github.ref_name }}
          ghcr.io/docker.pkg.github.com/qdrant/qdrant/qdrant:${{ github.ref_name }}
        push: true
