name: Run `prefault_mmap_pages` test on Windows

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-prefault-mmap-pages-windows-test:
    runs-on: windows-latest

    steps:

    - name: Intall Protobuf compiler
      uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout Qdrant repository
      uses: actions/checkout@v3
      with:
        path: qdrant

    - name: Checkout BFB repository
      uses: actions/checkout@v3
      with:
        repository: qdrant/bfb
        path: bfb

    - name: Run `prefault_mmap_pages` test on Windows
      shell: bash
      run: bash ./qdrant/tests/prefault-mmap-pages.sh qdrant bfb
