name: Formatter and linter

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 1.75 is the MSRV, https://github.com/qdrant/qdrant/pull/3315
        rust-version: [ "1.75", stable ]
      fail-fast: false
    steps:
    - name: Install minimal nightly (only for fmt)
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt
    - name: Install rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust-version }}
        components: rustfmt, clippy
    - uses: actions/checkout@v4
    - name: Install Protoc
      uses: arduino/setup-protoc@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: Swatinem/rust-cache@v2
      with:
        key: clippy
    - name: Install dependencies
      run: sudo apt-get install clang libunwind-dev
    - name: Check code formatting
      run: cargo +nightly fmt --all -- --check
    - name: Check cargo clippy warnings
      run: cargo clippy --workspace --all-targets --all-features -- -D warnings
