name: Storage compatibility tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get install clang libopenblas-dev libgfortran-10-dev gfortran git-lfs
      - name: Setup git-lfs
        run: git lfs install
      - name: Install minimal stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Run storage compatibility test
        run: |
          ./tests/storage-compat/storage-compatibility.sh
        shell: bash
